### ISSUE TITLE
ModuleNotFoundError: No module named 'npf.types.web'

### ISSUE THREAD

**Issue by Qcloud1223** [tbarbette/npf#40]
Hi! I installed NPF directly from `pip`, but when I tried to run it, it gives the following error:

```shell
$ npf-run
Traceback (most recent call last):
  File "/home/user/.local/bin/npf-run", line 5, in <module>
    from npf_run import main
  File "/home/user/.local/lib/python3.8/site-packages/npf_run.py", line 11, in <module>
    from npf.regression import *
  File "/home/user/.local/lib/python3.8/site-packages/npf/regression.py", line 3, in <module>
    from npf.grapher import *
  File "/home/user/.local/lib/python3.8/site-packages/npf/grapher.py", line 9, in <module>
    from npf.types.web.web import prepare_web_export
ModuleNotFoundError: No module named 'npf.types.web'
```

I've already export `~/.local/bin` to `PATH` so that `npf-run` can run directly. But that does not seems enough.

Here is my NPF version:

```
$ pip list | grep npf
npf                    1.0.50              
npf-web-extension      0.6.4
```

And here is what `pip` says when installing:

```
$ pip install --user npf
Requirement already satisfied: npf in /home/user/.local/lib/python3.8/site-packages (1.0.50)
Requirement already satisfied: numpy in /home/user/.local/lib/python3.8/site-packages (from npf) (1.24.4)
Requirement already satisfied: scipy in /home/user/.local/lib/python3.8/site-packages (from npf) (1.10.1)
Requirement already satisfied: importlib-metadata in /home/user/.local/lib/python3.8/site-packages (from npf) (6.8.0)
Requirement already satisfied: npf-web-extension>=0.6.4 in /home/user/.local/lib/python3.8/site-packages (from npf) (0.6.4)
Requirement already satisfied: scikit-learn in /home/user/.local/lib/python3.8/site-packages (from npf) (1.3.0)
Requirement already satisfied: asteval in /home/user/.local/lib/python3.8/site-packages (from npf) (0.9.31)
Requirement already satisfied: typing in /home/user/.local/lib/python3.8/site-packages (from npf) (3.7.4.3)
Requirement already satisfied: packaging in /home/user/.local/lib/python3.8/site-packages (from npf) (23.1)
Requirement already satisfied: matplotlib in /home/user/.local/lib/python3.8/site-packages (from npf) (3.7.2)
Requirement already satisfied: pandas in /home/user/.local/lib/python3.8/site-packages (from npf) (2.0.3)
Requirement already satisfied: pyasn1 in /home/user/.local/lib/python3.8/site-packages (from npf) (0.5.0)
Requirement already satisfied: pydotplus in /home/user/.local/lib/python3.8/site-packages (from npf) (2.0.2)
Requirement already satisfied: require-python-3 in /home/user/.local/lib/python3.8/site-packages (from npf) (1)
Requirement already satisfied: webcolors in /home/user/.local/lib/python3.8/site-packages (from npf) (1.13)
Requirement already satisfied: paramiko in /usr/lib/python3/dist-packages (from npf) (2.6.0)
Requirement already satisfied: gitpython in /home/user/.local/lib/python3.8/site-packages (from npf) (3.1.32)
Requirement already satisfied: colorama in /usr/lib/python3/dist-packages (from npf) (0.4.3)
Requirement already satisfied: pygtrie in /home/user/.local/lib/python3.8/site-packages (from npf) (2.5.0)
Requirement already satisfied: natsort in /home/user/.local/lib/python3.8/site-packages (from npf) (8.4.0)
Requirement already satisfied: regex in /home/user/.local/lib/python3.8/site-packages (from npf) (2023.6.3)
Requirement already satisfied: cryptography==41.0.0 in /home/user/.local/lib/python3.8/site-packages (from npf) (41.0.0)
Requirement already satisfied: gitdb in /home/user/.local/lib/python3.8/site-packages (from npf) (4.0.10)
Requirement already satisfied: ordered-set; python_version >= "3.7.0" in /home/user/.local/lib/python3.8/site-packages (from npf) (4.1.0)
Requirement already satisfied: zipp>=0.5 in /home/user/.local/lib/python3.8/site-packages (from importlib-metadata->npf) (3.16.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/user/.local/lib/python3.8/site-packages (from scikit-learn->npf) (3.2.0)
Requirement already satisfied: joblib>=1.1.1 in /home/user/.local/lib/python3.8/site-packages (from scikit-learn->npf) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (0.11.0)
Requirement already satisfied: contourpy>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (1.1.0)
Requirement already satisfied: fonttools>=4.22.0 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (4.41.1)
Requirement already satisfied: python-dateutil>=2.7 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (2.8.2)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (3.0.9)
Requirement already satisfied: pillow>=6.2.0 in /usr/lib/python3/dist-packages (from matplotlib->npf) (7.0.0)
Requirement already satisfied: importlib-resources>=3.2.0; python_version < "3.10" in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (6.0.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/user/.local/lib/python3.8/site-packages (from matplotlib->npf) (1.4.4)
Requirement already satisfied: pytz>=2020.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->npf) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/user/.local/lib/python3.8/site-packages (from pandas->npf) (2023.3)
Requirement already satisfied: cffi>=1.12 in /home/user/.local/lib/python3.8/site-packages (from cryptography==41.0.0->npf) (1.15.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/user/.local/lib/python3.8/site-packages (from gitdb->npf) (5.0.0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.7->matplotlib->npf) (1.14.0)
Requirement already satisfied: pycparser in /home/user/.local/lib/python3.8/site-packages (from cffi>=1.12->cryptography==41.0.0->npf) (2.21)
```

I'm not really familar with Python, and sorry if I missed some basic steps. Thank you!

**Comment by tbarbette** [comment]
It seems I pushed a temporary branch to pip. I'll fix that tomorrow, can you try the git version meanwhile?

**Comment by Qcloud1223** [comment]
Yes, the git version runs without any problem, thanks!

**Comment by tbarbette** [comment]
Ok I pushed the correct branch on pip, sorry about that.
